

send_texts_every_minute:
  cron: "* * * * *"
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1h
  # By default the job name (hash key) will be taken as worker class name.
  # If you want to have a different job name and class name, provide the 'class' option
  class: "TextsWorker"
  queue: high
  args:
  description: "This checks for moments every minute"



schedules_moments_at_local_midnight:
  cron: "0,30 * * * *"
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1h
  # By default the job name (hash key) will be taken as worker class name.
  # If you want to have a different job name and class name, provide the 'class' option
  class: "MomentsScheduler"
  queue: high
  args:
  description: "This checks for users at midnight locally and schedules day's moments"

